### ISSUE TITLE
puller update older remote ancestor(#39) after pusher uploads latest(#40) revision

### ISSUE THREAD

**Issue by jayahariv** [couchbase/couchbase-lite-core#669]
<img width="457" alt="screen shot 2019-01-22 at 4 10 57 pm" src="https://user-images.githubusercontent.com/10448770/51573940-5ef02180-1e60-11e9-802b-670f3da23e57.png">

what happens, 
1. Rev#39 is pushed to SG successfully. 
2. Rev#40 is uploaded to SG successfully. 
3. Rev#39 is marked as remote ancestor of document. [updateRemoteRev](https://github.com/couchbase/couchbase-lite-core/blob/bbda7c3e8b2cfc60ad88cadbe29ddf0dc33ed86e/Replicator/DBWorker.cc#L631)
4. Locally update the document and create revisions Rev#41,Rev#42, Rev#43, Rev#44 all with ancestor 39. 
4. Rev#44 is trying to be pushed to SG, with ancestor 39. 

Logs for this can be found in the [CBSE-6233](https://issues.couchbase.com/browse/CBSE-6233), attached log named "iPad.txt".

**Comment by snej** [comment]
Ouch, that's definitely a bug. Thanks for the clear diagram!

**Comment by jayahariv** [comment]
if you are inspecting the log("iPad.txt"), you can check for the docID `-Ng4XH7eU6ZJxTFcy598IkJ`

**Comment by snej** [comment]
```
00:53:18.775038+0530 ... {IncomingRev#82} Received revision '-qV3qwYHVN9osGu2rIgto2q' #39-7212636e41d3e38089242f476cdf3811 (seq '92275')
00:53:18.908757+0530 ... {DBWorker#2}     {'-qV3qwYHVN9osGu2rIgto2q' #39-7212636e41d3e38089242f476cdf3811}
00:53:22.080375+0530 ... {DBWorker#2} Sending revision '-qV3qwYHVN9osGu2rIgto2q' #40-6c493afee24e5eda748cb0e3c4e138f6821cfe17
00:53:23.882380+0530 ... KeyStore(default) update -qV3qwYHVN9osGu2rIgto2q
00:53:24.146547+0530 ... {DBWorker#2} Notified of 2 db changes #26947 ... #26948
00:53:24.150187+0530 ... {DBWorker#2} Notified of 1 db changes #26949 ... #26949
00:53:24.152863+0530 ... {Push#4} Completed rev -qV3qwYHVN9osGu2rIgto2q #40-6c493afee24e5eda748cb0e3c4e138f6821cfe17 (seq #26932)
00:53:24.153163+0530 ... {DBWorker#2} Notified of 3 db changes #26950 ... #26952
00:53:24.545580+0530 ... {Push#4} Read 3 local changes up to #26952: sending 'proposeChanges' with sequences #26950 - #26952
00:53:27.197501+0530 ... {Push#4} Got response for 3 local changes (sequences from 26950)
00:53:27.199542+0530 ... {Push#4} Proposed rev '-qV3qwYHVN9osGu2rIgto2q' #41-0f6121485b4739dc632cb4676713db806c8b8fbc (ancestor 39-7212636e41d3e38089242f476cdf3811) rejected with status 409
```

(The three "`Notified of … db changes`" messages are from one call to `DBWorker::dbChanged`.)

**Comment by snej** [comment]
(I'm looking at doc `-Ng4XH7eU6ZJxTFcy598IkJ`, which seems to have similar stuff going on.)

**Comment by snej** [comment]
* at 00:53:23.823255, rev 39 is marked as the current remote.
* at 00:53:24.152863, rev 40 is done and queues a request to mark that as the current remote.
* at 00:53:24.153163, the three new sequences including rev 41 are read from the db, including their current-remote properties; so rev 41 will be sent with rev 39 as the remote parent.

The problem is that the current-remove-rev property doesn't have "read your own writes" consistency, because of the queuing/batching behavior of DBWorker::markRevSynced. I've tried to work around that by calling `_markRevsSyncedNow` at the start of operations that access that property, but that only makes races less likely...

**Comment by borrrden** [comment]
Could you have some "recovery logic" when the conflict happens that attempts to do something similar?

**Comment by snej** [comment]
I fixed the problem by ensuring that a new rev will not even start being pushed until an earlier rev of the same document is completely finished. This required moving some logic from Pusher to DBWorker (see `DBWorker::_pushingDocs`).

**Comment by srinadh-k** [comment]
@jayahariv or @snej  When this bug fix will available to end clients? I have filed this bug in support couchbase site and it was a production issue to us.

**Comment by snej** [comment]
It'll be in the next release (2.5?) I don't think we've announced a schedule for it yet.
Reminder: As a Couchbase customer you should talk to Support about issues like this.

**Comment by srinadh-k** [comment]
Sure, Thanks for update

**Comment by jayahariv** [comment]
Hi @snej, 
After validating the fix we added last time, seems like the issue is still happening. The new revision(Rev#31) is saved(and using the ancestor as Rev#29) before the previous revision(Rev#30) push is completed. 

```
// save #30 
2019-02-04 17:31:52.702241+0530 CC Bridge Dev[11546:336051] CouchbaseLite Query Verbose: {QueryEnum#547} --> ["-SctbHJteeYMsAWZ_cxDzG-"]
2019-02-04 17:31:52.870661+0530 CC Bridge Dev[11546:336051] CouchbaseLite Database Verbose: {DB#1} Saved '-SctbHJteeYMsAWZ_cxDzG-' rev #30-0aecbc1d4959072323d851cae9906e4ef1c7f7dc as seq 12722

// queue #30
2019-02-04 17:31:54.637481+0530 CC Bridge Dev[11546:348636] CouchbaseLite Replicator Verbose: {Push#3} Queueing rev '-SctbHJteeYMsAWZ_cxDzG-' #30-0aecbc1d4959072323d851cae9906e4ef1c7f7dc (seq #12722) [1 queued]

// sending doc #30
2019-02-04 17:31:54.637660+0530 CC Bridge Dev[11546:348636] CouchbaseLite Replicator Verbose: {Push#3} Sending rev -SctbHJteeYMsAWZ_cxDzG- 30-0aecbc1d4959072323d851cae9906e4ef1c7f7dc (seq #12722) [2/10]
2019-02-04 17:31:54.641724+0530 CC Bridge Dev[11546:348752] CouchbaseLite Replicator Verbose: {DBWorker#2} Reading document '-SctbHJteeYMsAWZ_cxDzG-' #30-0aecbc1d4959072323d851cae9906e4ef1c7f7dc
2019-02-04 17:31:54.642417+0530 CC Bridge Dev[11546:348752] CouchbaseLite Replicator Verbose: {DBWorker#2} Transmitting 'rev' message with '-SctbHJteeYMsAWZ_cxDzG-' #30-0aecbc1d4959072323d851cae9906e4ef1c7f7dc


// save #31 (guessing this will point to ancestor #29)
2019-02-04 17:31:54.728073+0530 CC Bridge Dev[11546:348185] CouchbaseLite Query Verbose: {QueryEnum#559} --> ["-SctbHJteeYMsAWZ_cxDzG-"]
2019-02-04 17:31:54.730735+0530 CC Bridge Dev[11546:348185] CouchbaseLite Database Verbose: {DB#1} Saved '-SctbHJteeYMsAWZ_cxDzG-' rev #31-b6b82235c1a07e2edcccd3c54c899f181240bfbe as seq 12726

// completed #30 
2019-02-04 17:31:55.535579+0530 CC Bridge Dev[11546:348813] CouchbaseLite Replicator Verbose: {Push#3} Completed rev -SctbHJteeYMsAWZ_cxDzG- #30-0aecbc1d4959072323d851cae9906e4ef1c7f7dc (seq #12722)

// proposed revision #31 rejected
2019-02-04 17:31:56.290209+0530 CC Bridge Dev[11546:348813] CouchbaseLite Replicator ERROR: {Push#3} Proposed rev '-SctbHJteeYMsAWZ_cxDzG-' #31-b6b82235c1a07e2edcccd3c54c899f181240bfbe (ancestor 29-c002dce6e62609ab2920a307cf7e52c7) rejected with status 409
2019-02-04 17:31:56.290827+0530 CC Bridge Dev[11546:348813] CouchbaseLite Replicator Info: {Repl#1} documentEnded -SctbHJteeYMsAWZ_cxDzG- 31-b6b82235c1a07e2edcccd3c54c899f181240bfbe flags=00 (6/409)
2019-02-04 17:31:56.293387+0530 CC Bridge Dev[11546:348752] CouchbaseLite Replicator WARNING: {DBWorker#2} _donePushingRev('-SctbHJteeYMsAWZ_cxDzG-'): That docID is not active!
2019-02-04 17:31:56.768666+0530 CC Bridge Dev[11546:348813] CouchbaseLite Replicator Info: CBLReplicator[<*> URL[ws://ec2-100-26-245-235.compute-1.amazonaws.com:4984/costalerts/]]: error pushing '-SctbHJteeYMsAWZ_cxDzG-': 6/409
```

Whole logs are in Jira [CBSE 6233](https://issues.couchbase.com/browse/CBSE-6233)

**Comment by snej** [comment]
May be related to #689, #690...

**Comment by snej** [comment]
@borrrden and I found a bug in that fix (65ca46f) — the fix for the fix is ed82fb3. I suspect it will fix this too.

**Comment by pasin** [comment]
The issue still persists after using the latest fix. The latest [log](https://issues.couchbase.com/secure/attachment/64293/64293_Feb6-iPad.txt) doesn't have Database domain enabled but the same conflict error pattern could be noticed.

From the log, check the document ID = "-2lMuYdeTm1rhpOwkIKG_l".

1. The revision #29-4ae7ea2e1e524c7d83f17ecaa1d98356 was successfully pulled.
2. The revision #30-7cbce32fbf14a6e3cecf65fe7c9824da2658c577 was successfull pushed.
3. The revision #31-8698f182434c7f8f83a0893ffb8016c0ec630798 (ancestor 29-4ae7ea2e1e524c7d83f17ecaa1d98356) was failed to push with status 409.

**Comment by pasin** [comment]
I don't know if this is relevant or not. I have seen rev 30 got queued to push in the log as below but not rev 31.

```
CouchbaseLite Replicator Verbose: {Push#27} Queueing rev '-2lMuYdeTm1rhpOwkIKG_lU' #30-7cbce32fbf14a6e3cecf65fe7c9824da2658c577 (seq #20012) [1 queued]
```

**Comment by jayahariv** [comment]
```
2019-02-06 15:22:25.460308+0530 CC Bridge Dev[9812:218751] CouchbaseLite Replicator Verbose: {DBWorker#1} Notified of 1 db changes #20017 ... #20017
2019-02-06 15:22:25.622776+0530 CC Bridge Dev[9812:218647] CouchbaseLite Replicator Verbose: {Push#27} Completed rev -2lMuYdeTm1rhpOwkIKG_lU #30-7cbce32fbf14a6e3cecf65fe7c9824da2658c577 (seq #20012)
2019-02-06 15:22:25.623410+0530 CC Bridge Dev[9812:218647] CouchbaseLite Replicator Info: {Push#27} Read 1 local changes up to #20017: sending 'proposeChanges' with sequences #20017 - #20017
2019-02-06 15:22:26.043040+0530 CC Bridge Dev[9812:218647] CouchbaseLite Replicator Info: {Push#27} Got response for 1 local changes (sequences from 20017)
2019-02-06 15:22:26.044009+0530 CC Bridge Dev[9812:218647] CouchbaseLite Replicator ERROR: {Push#27} Proposed rev '-2lMuYdeTm1rhpOwkIKG_lU' #31-8698f182434c7f8f83a0893ffb8016c0ec630798 (ancestor 29-4ae7ea2e1e524c7d83f17ecaa1d98356) rejected with status 409
2019-02-06 15:22:26.044304+0530 CC Bridge Dev[9812:218647] CouchbaseLite Replicator Info: {Repl#3} documentEnded -2lMuYdeTm1rhpOwkIKG_lU 31-8698f182434c7f8f83a0893ffb8016c0ec630798 flags=00 (6/409)
2019-02-06 15:22:26.044981+0530 CC Bridge Dev[9812:218647] CouchbaseLite Replicator Verbose: {Push#27} progress +1150/+0, 0 docs -- now 14497 / 14709, 17 docs
2019-02-06 15:22:26.045166+0530 CC Bridge Dev[9812:218647] CouchbaseLite Replicator Info: {Push#27} activityLevel=busy: pendingResponseCount=0, caughtUp=1, changeLists=0, revsInFlight=0, blobsInFlight=0, awaitingReply=395, revsToSend=0, pendingSequences=3
2019-02-06 15:22:26.269676+0530 CC Bridge Dev[9812:218543] CouchbaseLite Replicator Verbose: {Push#27} Completed rev -WBJu6PcG19XYFv666Bt2ON #1-dca0205a73e7813ddc966f31db14f33fbb41eb1c (seq #20016)
2019-02-06 15:22:26.269786+0530 CC Bridge Dev[9812:218543] CouchbaseLite Replicator Verbose: {Push#27} progress +212/+0, 1 docs -- now 14709 / 14709, 18 docs
2019-02-06 15:22:26.269947+0530 CC Bridge Dev[9812:218543] CouchbaseLite Replicator Info: {Push#27} activityLevel=idle: pendingResponseCount=0, caughtUp=1, changeLists=0, revsInFlight=0, blobsInFlight=0, awaitingReply=0, revsToSend=0, pendingSequences=2
2019-02-06 15:22:26.270146+0530 CC Bridge Dev[9812:218543] CouchbaseLite Replicator Verbose: {Push#27} now idle
```

1. Seq#20017 is the local change which is rejected. It is notified. This includes the ancestor Rev#29. 
2. Completed the Rev#30, Seq#20012 
3. Got response for the Seq#20017
4. Rev#31 - Rejected!
5. Progress status shows 14497 / 14709. 17 docs. 
6. Completed different revision. Now the progress is 14709 / 14709, 18 docs.

Is this correct? when there is a document rejection happened, and one document is not yet pushed to SG. Progress status should say, completed less than the total? In this case it is saying 14709 / 14709, when the next revision completes.

**Comment by snej** [comment]
@pasin: "Queueing rev..." is logged when the pusher decides to send the revision body. Rev 31 never got that far because it was rejected by the server.

I really wish DB logging were turned on so we could see what doc/rev IDs the sequences correspond to. I agree with @jayahariv that sequence 20017 is rev 30, but we don't have proof.

**Comment by pasin** [comment]
I'm trying to match the log and the code path with some guess. The suspicious path that could cause the remote ancestor of the `Rev 31` to be changed after being set to `Rev 30` in this [line](https://github.com/couchbase/couchbase-lite-core/blob/bd6414dc8df9c5c99cf36de6ad8adbd346160561/Replicator/DBWorker.cc#L1167) is [here](https://github.com/couchbase/couchbase-lite-core/blob/bd6414dc8df9c5c99cf36de6ad8adbd346160561/Replicator/DBWorker.cc#L499-L507). 

Note: I assumed that the previous fix works so the Rev-31 was re-queued after Rev-30 was completely pushed (From the log, it seemed like that).
